// Generated by https://quicktype.io

export interface ItemResponse {
    author: Author;
    item:   ItemRes;
}

export interface Author {
    name:     string;
    lastName: string;
}

export interface ItemRes {
    id:            string;
    title:         string;
    picture:       string;
    condition:     string;
    sold_quantity: number;
    price:         Price;
    free_shipping: boolean;
    description:   string;
    categories: string[]
}

export interface Price {
    currency: string;
    amount:   number;
    decimals: number;
}
